[package]
name = "unc-actix-test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
actix-rt.workspace = true
futures.workspace = true
once_cell.workspace = true

unc-store.workspace = true

[features]
nightly = [
  "nightly_protocol",
  "unc-store/nightly",
]
nightly_protocol = [
  "unc-store/nightly_protocol",
]
