[package]
name = "unc-jsonrpc-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
actix.workspace = true
awc.workspace = true
once_cell.workspace = true
futures.workspace = true
borsh.workspace = true
serde.workspace = true
serde_json.workspace = true

unc-chain-configs.workspace = true
unc-crypto.workspace = true
unc-primitives.workspace = true
unc-client.workspace = true
unc-store.workspace = true
unc-o11y.workspace = true
unc-network.workspace = true
unc-jsonrpc.workspace = true
unc-jsonrpc-primitives.workspace = true

[dev-dependencies]
unc-actix-test-utils.workspace = true

[features]
test_features = ["unc-jsonrpc/test_features"]
nightly = [
  "nightly_protocol",
  "unc-chain-configs/nightly",
  "unc-client/nightly",
  "unc-jsonrpc-primitives/nightly",
  "unc-jsonrpc/nightly",
  "unc-network/nightly",
  "unc-o11y/nightly",
  "unc-primitives/nightly",
  "unc-store/nightly",
]
nightly_protocol = [
  "unc-chain-configs/nightly_protocol",
  "unc-client/nightly_protocol",
  "unc-jsonrpc-primitives/nightly_protocol",
  "unc-jsonrpc/nightly_protocol",
  "unc-network/nightly_protocol",
  "unc-o11y/nightly_protocol",
  "unc-primitives/nightly_protocol",
  "unc-store/nightly_protocol",
]
sandbox = ["unc-jsonrpc/sandbox"]
