[package]
name = "unc-mainnet-res"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
serde_json.workspace = true

unc-account-id.workspace = true
unc-chain-configs.workspace = true
unc-primitives.workspace = true

[features]
nightly = [
  "nightly_protocol",
  "unc-chain-configs/nightly",
  "unc-primitives/nightly",
]
nightly_protocol = [
  "unc-chain-configs/nightly_protocol",
  "unc-primitives/nightly_protocol",
]
