[package]
name = "unc-wallet-contract"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Builds and exposes Wallet Contract code."
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
unc-vm-runner.workspace = true

[dev-dependencies]
unc-primitives-core.workspace = true

[build-dependencies]
anyhow.workspace = true

[features]
nightly_protocol = [
  "unc-vm-runner/nightly_protocol",
]
nightly = [
  "nightly_protocol",
  "unc-vm-runner/nightly",
]
