[package]
name = "unc-jsonrpc-fuzz"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
actix.workspace = true
arbitrary.workspace = true
awc.workspace = true
libfuzzer-sys.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

unc-jsonrpc.workspace = true
unc-jsonrpc-primitives.workspace = true
unc-jsonrpc-tests.workspace = true
unc-primitives.workspace = true

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets_disabled/fuzz_target_1.rs"
test = false
doc = false
