[package]
name = "unc-rpc-error-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "This crate generates schema for Rust structs which can be used by TypeScript."
repository.workspace = true
license.workspace = true
publish = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true, features = ["preserve_order"] }
syn.workspace = true
fs2.workspace = true

unc-rpc-error-core.workspace = true

[features]
test = []
dump_errors_schema = ["unc-rpc-error-core/dump_errors_schema", "serde_json"]
