name: Unc Crates Publish

on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:

jobs:
  publish-cargo-crates:
    name: "Publish unc-workspaces on crates.io https://crates.io/crates/unc-workspaces"
    runs-on: "ubuntu-latest"
    environment: deploy
    permissions:
      contents: write # required for crates push
    timeout-minutes: 30 
    
    steps:
      - name: Checkout jong-un-crypto/unc's ${{ github.event.inputs.branch }} branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Set up git user
        uses: fregante/setup-git-user@v2
      - name: Publish unc-workspaces on crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          set -x
          cargo install --git https://github.com/miraclx/cargo-workspaces --tag v0.3.0 cargo-workspaces
          cargo ws publish --yes --allow-dirty --force '*' \
              --no-git-commit --no-git-push --no-individual-tags --tag-prefix 'crates-' \
              --tag-msg $$'crates.io snapshot\n---%{\n- %n - https://crates.io/crates/%n/%v}'

      - name: Create tag on https://github.com/jong-un-crypto/unc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --no-follow-tags https://github.com/jong-un-crypto/unc.git tag 'crates-*'
